---
- name: Deprovision httpd on CentOS
  hosts: all  # Replace with your target hosts or group
  become: yes  # Run tasks as sudo

  tasks:
    - name: Stop httpd service
      systemd:
        name: httpd
        state: stopped

    - name: Uninstall httpd
      package:
        name: httpd
        state: absent

    - name: Remove httpd config files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/httpd/conf/httpd.conf
        - /etc/httpd/conf.d/*  # Caution, this removes all custom configs in conf.d

    - name: Reload systemd to reflect changes
      systemd:
        daemon_reload: yes
